# Generated by Django 4.1 on 2022-09-04 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingcourse',
            name='teaching',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='courses_of_teaching', to='university.teaching'),
        ),
        migrations.AddField(
            model_name='studentsemester',
            name='semester',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='semester_studentsemester', to='courses.semester'),
        ),
        migrations.AddField(
            model_name='studentsemester',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='status_studentsemester', to='courses.status'),
        ),
        migrations.AddField(
            model_name='studentsemester',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='semester_student', to='university.student'),
        ),
        migrations.AddField(
            model_name='studentdegree',
            name='degree',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='students_doing_degree', to='courses.degree'),
        ),
        migrations.AddField(
            model_name='studentdegree',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='status_studentdegree', to='courses.status'),
        ),
        migrations.AddField(
            model_name='studentdegree',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='degrees_of_student', to='university.student'),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='students_doing_course', to='courses.course'),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='grade',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='students_with_grade', to='courses.grade'),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='semester',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='studentsemester_courses', to='courses.studentsemester'),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='status_studentcourse', to='courses.status'),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='courses_of_student', to='university.student'),
        ),
        migrations.AddField(
            model_name='historicalteachingcourse',
            name='course',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.course'),
        ),
        migrations.AddField(
            model_name='historicalteachingcourse',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalteachingcourse',
            name='teaching',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='university.teaching'),
        ),
        migrations.AddField(
            model_name='historicalstudentsemester',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalstudentsemester',
            name='semester',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.semester'),
        ),
        migrations.AddField(
            model_name='historicalstudentsemester',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.status'),
        ),
        migrations.AddField(
            model_name='historicalstudentsemester',
            name='student',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='university.student'),
        ),
        migrations.AddField(
            model_name='historicalstudentdegree',
            name='degree',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.degree'),
        ),
        migrations.AddField(
            model_name='historicalstudentdegree',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalstudentdegree',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.status'),
        ),
        migrations.AddField(
            model_name='historicalstudentdegree',
            name='student',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='university.student'),
        ),
        migrations.AddField(
            model_name='historicalstudentcourse',
            name='course',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.course'),
        ),
        migrations.AddField(
            model_name='historicalstudentcourse',
            name='grade',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.grade'),
        ),
        migrations.AddField(
            model_name='historicalstudentcourse',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalstudentcourse',
            name='semester',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.studentsemester'),
        ),
        migrations.AddField(
            model_name='historicalstudentcourse',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.status'),
        ),
        migrations.AddField(
            model_name='historicalstudentcourse',
            name='student',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='university.student'),
        ),
        migrations.AddField(
            model_name='degree',
            name='dept',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='degrees_from_dept', to='courses.department'),
        ),
        migrations.AddField(
            model_name='current',
            name='currentSemester',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='current_semeter', to='courses.semester'),
        ),
        migrations.AddField(
            model_name='course',
            name='degree',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='courses_in_degree', to='courses.degree'),
        ),
        migrations.AddField(
            model_name='course',
            name='dept',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='courses_in_dept', to='courses.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='schedule',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='courses_on_schedule', to='courses.schedule'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester_offered',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='courses_in_semester', to='courses.semester'),
        ),
    ]
