# Generated by Django 4.1 on 2022-09-05 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('lecture_url', models.URLField()),
                ('notes', models.URLField()),
                ('name', models.CharField(max_length=15)),
                ('course', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='course_content', to='courses.course')),
            ],
        ),
    ]
