# Generated by Django 3.1.4 on 2022-07-31 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_studentcourse_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='semester',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='semester_studentcourse', to='courses.semester'),
        ),
    ]
