# Generated by Django 5.1.1 on 2024-10-04 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudentdegree',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.status'),
        ),
        migrations.AlterField(
            model_name='studentdegree',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='status_studentdegree', to='courses.status'),
        ),
    ]
