# Generated by Django 3.1.4 on 2022-08-06 22:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_auto_20220718_0302'),
        ('courses', '0004_auto_20220731_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 8, 6, 22, 47, 42, 731717, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentdegree',
            name='cgpa',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdegree',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 8, 6, 22, 47, 57, 589216, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdegree',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='students_doing_course', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='courses_of_student', to='university.student'),
        ),
        migrations.AlterField(
            model_name='studentdegree',
            name='degree',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='students_doing_degree', to='courses.degree'),
        ),
        migrations.AlterField(
            model_name='studentdegree',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='degrees_of_student', to='university.student'),
        ),
        migrations.CreateModel(
            name='StudentSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('semester', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='semester_studentsemester', to='courses.semester')),
                ('student', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='semester_student', to='university.student')),
            ],
        ),
    ]
