# Generated by Django 5.1.1 on 2024-10-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_historicalstudentdegree_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudentdegree',
            name='cgpa',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='historicalstudentdegree',
            name='completed_date',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='historicalstudentdegree',
            name='credits_achieved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentdegree',
            name='cgpa',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='studentdegree',
            name='completed_date',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='studentdegree',
            name='credits_achieved',
            field=models.IntegerField(default=0),
        ),
    ]
