# Generated by Django 3.1.4 on 2022-08-06 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_auto_20220718_0302'),
        ('courses', '0005_auto_20220806_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='teching_course', to='courses.course')),
                ('teaching', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='courses_of_teaching', to='university.teaching')),
            ],
        ),
    ]
