# Generated by Django 5.1.1 on 2024-10-04 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_historicalstudentdegree_completed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudentdegree',
            name='completed_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='studentdegree',
            name='completed_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
