# Generated by Django 3.1.4 on 2022-08-06 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_teachingcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
                ('monday', models.BooleanField()),
                ('tuesday', models.BooleanField()),
                ('wednesday', models.BooleanField()),
                ('thursday', models.BooleanField()),
                ('friday', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='schedule',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='courses_on_schedule', to='courses.schedule'),
        ),
    ]
