# Generated by Django 5.1.1 on 2024-10-11 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_historicalstudentdegree_completed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudentcourse',
            name='grade',
            field=models.ForeignKey(blank=True, db_constraint=False, default='Def', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.grade'),
        ),
        migrations.AlterField(
            model_name='historicalstudentcourse',
            name='semester',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.studentsemester'),
        ),
        migrations.AlterField(
            model_name='historicalstudentcourse',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.status'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='grade',
            field=models.ForeignKey(default='Def', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='students_with_grade', to='courses.grade'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='studentsemester_courses', to='courses.studentsemester'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='status_studentcourse', to='courses.status'),
        ),
    ]
