# Generated by Django 5.1.1 on 2024-10-11 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_historicalstudentcourse_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudentcourse',
            name='grade',
            field=models.ForeignKey(blank=True, db_constraint=False, default=13, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.grade'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='grade',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='students_with_grade', to='courses.grade'),
        ),
    ]
