# Generated by Django 3.1.4 on 2022-08-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20220806_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsemester',
            name='sgpa',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
            preserve_default=False,
        ),
    ]
