# Generated by Django 3.1.4 on 2022-08-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_studentsemester_sgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsemester',
            name='status',
            field=models.CharField(default='Applied', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='status',
            field=models.CharField(default='Applied', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentdegree',
            name='status',
            field=models.CharField(default='Applied', max_length=10),
        ),
    ]
