# Generated by Django 3.1.4 on 2022-08-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20220806_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
