# Generated by Django 3.1.4 on 2022-08-07 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20220807_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester_offered',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='courses_in_semester', to='courses.semester'),
        ),
    ]
