# Generated by Django 3.1.4 on 2022-08-07 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_semester_offered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='schedule',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='courses_on_schedule', to='courses.schedule'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester_offered',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='courses_in_semester', to='courses.semester'),
        ),
    ]
