# Generated by Django 3.1.4 on 2022-08-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20220807_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
