# Generated by Django 3.1.4 on 2022-08-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20220807_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('value', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
