# Generated by Django 3.1.4 on 2022-08-08 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20220807_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudentcourse',
            name='grade',
            field=models.ForeignKey(blank=True, db_constraint=False, default='Def', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.grade'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='grade',
            field=models.ForeignKey(default='Def', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='students_with_grade', to='courses.grade'),
        ),
    ]
