# Generated by Django 4.1 on 2022-08-21 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_auto_20220808_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudentdegree',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.status'),
        ),
        migrations.AlterField(
            model_name='historicalstudentsemester',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.status'),
        ),
        migrations.AlterField(
            model_name='studentdegree',
            name='status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='status_studentdegree', to='courses.status'),
        ),
        migrations.AlterField(
            model_name='studentsemester',
            name='status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='status_studentsemester', to='courses.status'),
        ),
    ]
