# Generated by Django 4.1 on 2022-08-21 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_alter_historicalstudentdegree_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudentcourse',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.status'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='status_studentcourse', to='courses.status'),
        ),
    ]
