# Generated by Django 4.1 on 2022-08-23 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_alter_historicalstudentcourse_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Current',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentDateTime', models.DateTimeField()),
                ('currentSemester', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='current_semeter', to='courses.semester')),
            ],
        ),
    ]
