# Generated by Django 4.1 on 2022-08-23 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudentsemester',
            name='enrollment_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='studentsemester',
            name='enrollment_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
