# Generated by Django 3.1.4 on 2022-07-18 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20220718_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='staff_at_address', to='university.address'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_of_gender', to='university.gender'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address_current',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='students_at_current_address', to='university.address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address_home',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='students_at_home_address', to='university.address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_of_gender', to='university.gender'),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='teaching_at_address', to='university.address'),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_of_gender', to='university.gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='users_of_type', to='university.usertype'),
        ),
    ]
