# Generated by Django 5.1.1 on 2024-09-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_remove_address_address_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apt',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
