# Generated by Django 3.1.4 on 2022-08-07 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_auto_20220718_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address_current',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='students_at_current_address', to='university.address'),
        ),
    ]
