# Generated by Django 5.1.1 on 2024-10-04 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_alter_address_apt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaching',
            name='age',
        ),
    ]
