# Generated by Django 5.1.1 on 2024-11-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='university/photos/profile-image-placeholder.jpeg', upload_to='university/photos'),
        ),
    ]
