# Generated by Django 5.1.1 on 2024-11-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default='This is the bio section'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='media/university/photos/profile-image-placeholder.jpeg', upload_to='media/university/photos'),
        ),
    ]
