# Generated by Django 5.1.1 on 2024-11-26 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_user_bio_alter_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='admin_at_address', to='university.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
